setup.v2.sh: Add install::verify_docker_installation (#56)
## 변경사항
- SCRIPT_VERSION="25.07.4"
- QPD-3079 docker 설치 전후 상태를 면밀히 살펴보고, docker 명령이 정상적으로 실행되는 상태를 만들어 주는
기능이 필요합니다.
- install::verify_docker_installation 함수를 구현하여, docker group 적용 여부 상태를
진단하고, 적절한 안내 메시지를 출력합니다.

## 기대효과
- docker 가 설치되지 않은 리눅스에서, docker 설치 과정을 적절히 안내합니다.

## 테스팅 결과
- docker 설치 후, `systemctl enable --now docker` 를 실행하지 않은 경우.
```
[ec2-user@ip-172-31-11-201 ~]$ ./setup.v2.sh --yes
### Install QueryPie version 11.0.0 ###
# Directory ./querypie/ does not exist. QueryPie has not been installed on this system.
Do you want to install QueryPie (11.0.0)?
Do you agree? [y/N] : yes
### Install QueryPie ###
# QP_VERSION: 11.0.0
# PACKAGE_VERSION: 11.0.x
#
## Configure sudo privileges
#
# 'sudo' will be used for privileged commands.
#
## Install Docker engine
#
# Docker is already installed at /usr/bin/docker
#
## Verify Docker installation
#
+ docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
ERROR: Failed to run: docker ps
# Docker installation verification failed. Please check above errors.
# Resolve the identified issues before proceeding.
[ec2-user@ip-172-31-11-201 ~]$ 
```