AMI 빌드 - querypie-ami.pkr.hcl 도입 (#21)
- HashiCorp Packer 를 이용하여, AMI 빌드를 자동화합니다.
  - HCL2 스크립트로 AMI 빌드 명세를 코드로 구현합니다.
- 구현된 상태
  - `build-ami.sh` 스크립트를 실행하면, `packer` 명령이 실행됩니다.
  - Amazon Linux 2023 을 Source AMI 로 사용합니다.
- 빌드용 SSH KeyPair 생성, EC2 Instance 생성, Security Group 생성 등 과정이 자동으로
진행됩니다.
  - AMI 빌드 과정 자체는, linux package 설치 과정에서 충돌이 발생하여 실패합니다.
  - `packer`는 빌드 과정에서 생성한 임시 자원을 모두 정리하고, 종료합니다.
- 실행결과

```
jk@Jk-Kim-VVVY6C7KYV aws-ami % ./build-ami.sh 10.3.0
### Build AMI with Packer ###
+ packer build -var querypie_version=10.3.0 -var ami_name_prefix=querypie-suite querypie-ami.pkr.hcl
build-querypie-ami.amazon-ebs.amazon-linux-2023: output will be in this color.

==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Prevalidating any provided VPC information
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Prevalidating AMI Name: querypie-suite-10.3.0-20250605130443
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Found Image ID: ami-0c12d48b7c30e8d8e
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Creating temporary keypair: packer_684195eb-a216-a454-71d1-d2339d0847a5
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Creating temporary security group for this instance: packer_684195ec-f6a9-726a-a85c-340337f11d5a
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Launching a source AWS instance...
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Instance ID: i-0fcbe354d007cca36
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Waiting for instance (i-0fcbe354d007cca36) to become ready...
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Using SSH communicator to connect: 52.78.151.189
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Waiting for SSH to become available...
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Connected to SSH!
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Provisioning with shell script: /var/folders/9h/bj4nh9ss6pq0_2bkd39t0p0w0000gn/T/packer-shell3565381109
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Waiting for cloud-init to complete...
==> build-querypie-ami.amazon-ebs.amazon-linux-2023:
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: status: done
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Cloud-init completed
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Provisioning with shell script: /var/folders/9h/bj4nh9ss6pq0_2bkd39t0p0w0000gn/T/packer-shell2230496802
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Starting system updates...
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Waiting for process with pid 1654 to finish.
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Amazon Linux 2023 Kernel Livepatch repository   131 kB/s |  16 kB     00:00
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Dependencies resolved.
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Nothing to do.
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Complete!
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Last metadata expiration check: 0:00:02 ago on Thu Jun  5 13:05:40 2025.
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Dependencies resolved.
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Nothing to do.
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Complete!
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Provisioning with shell script: /var/folders/9h/bj4nh9ss6pq0_2bkd39t0p0w0000gn/T/packer-shell1339410998
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Installing essential packages...
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Last metadata expiration check: 0:00:03 ago on Thu Jun  5 13:05:40 2025.
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Error:
==> build-querypie-ami.amazon-ebs.amazon-linux-2023:  Problem: problem with installed package curl-minimal-8.5.0-1.amzn2023.0.5.x86_64
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: (try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
==> build-querypie-ami.amazon-ebs.amazon-linux-2023:   - package curl-minimal-8.5.0-1.amzn2023.0.5.x86_64 from @System conflicts with curl provided by curl-7.87.0-2.amzn2023.0.2.x86_64 from amazonlinux

....

==> build-querypie-ami.amazon-ebs.amazon-linux-2023:   - package curl-minimal-8.5.0-1.amzn2023.0.5.x86_64 from amazonlinux conflicts with curl provided by curl-8.5.0-1.amzn2023.0.5.x86_64 from amazonlinux
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Provisioning step had errors: Running the cleanup provisioner, if present...
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Terminating the source AWS instance...
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Cleaning up any extra volumes...
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: No volumes to clean up, skipping
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Deleting temporary security group...
==> build-querypie-ami.amazon-ebs.amazon-linux-2023: Deleting temporary keypair...
Build 'build-querypie-ami.amazon-ebs.amazon-linux-2023' errored after 1 minute 31 seconds: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Wait completed after 1 minute 31 seconds

==> Some builds didn't complete successfully and had errors:
--> build-querypie-ami.amazon-ebs.amazon-linux-2023: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
ERROR: Failed to run: packer build -var querypie_version=10.3.0 -var ami_name_prefix=querypie-suite querypie-ami.pkr.hcl
### Get AMI ID ###
jk@Jk-Kim-VVVY6C7KYV aws-ami %  
```